<?php
/**
 * Created by PhpStorm.
 * User: 杨帆
 * Date: 2021/1/26
 * Time: 15:22
 */

class example extends base
{
    /**
     * 通过父类生成基本的架子
     *
     * @param   string  $newPath  新生成的目录地址 不建议更改
     * @param   string  $composerName  要获取的包名称 可以不带版本号
     */
    public static function run($newPath = 'src',$composerName='illuminate/validation v8.25')
    {
        parent::start($newPath,$composerName); // TODO: Change the autogenerated stub

        /**
         * 在骨架的基础上，针对不同的包继续进行一些额外的操作
         */
    }
}