<?php
/**
 * Created by PhpStorm.
 * User: 杨帆
 * Date: 2021/1/26
 * Time: 15:42
 */

require_once ('base.php');
class validation extends base
{
    /**
     * 通过父类生成基本的架子
     * @param   string  $newPath
     */
    public static function run($newPath = 'src',$composerName='illuminate/validation v8.25')
    {
        parent::start($newPath,$composerName); // TODO: Change the autogenerated stub

        /**
         * 在骨架的基础上，针对不同的包继续进行一些额外的操作
         */

        //生成中间处理文件和目录
        static::generateHandle($newPath);
    }

    private static function generateHandle($newPath)
    {
        $providePath=fileSystem::$bathDirPath.'ext'.DIRECTORY_SEPARATOR.$newPath.DIRECTORY_SEPARATOR.'provide';
        if(!is_dir($providePath)){
            if(mkdir($providePath,0777,true)===false){
                throw new \Exception('创建'.$providePath.'目录失败');
            }
        }
        $supportPath=$providePath.DIRECTORY_SEPARATOR.'support';
        if(!is_dir($supportPath)){
            if(mkdir($supportPath,0777,true)===false){
                throw new \Exception('创建'.$supportPath.'目录失败');
            }
        }


        $contents=static::baseContent();

        foreach (constant::$oldUniqueNameSpaceArray as $key => $value) {
            $contents = str_replace($value, constant::$newUniqueNameSpaceArray[$key], $contents);
        }
        $ValidationPath=$providePath.DIRECTORY_SEPARATOR.'Validation.php';


        $extendLoadPath=$supportPath.DIRECTORY_SEPARATOR.'ExtendLoad.php';
        if (file_put_contents($extendLoadPath, static::extendLoad()) === false) {
            throw new \Exception('写入文件失败:'.$extendLoadPath);
        }





        //生成中间验证器服务文件
        if (file_put_contents($ValidationPath, $contents) === false) {
            throw new \Exception('写入文件失败:'.$ValidationPath);
        }

        //生成语言包
        $langDirPath=$providePath.DIRECTORY_SEPARATOR.'lang'.DIRECTORY_SEPARATOR.'zn';
        if(!is_dir($langDirPath)){
            if(mkdir($langDirPath,0777,true)===false){
                throw new \Exception('创建'.$langDirPath.'目录失败');
            }
        }

        file_put_contents($langDirPath.DIRECTORY_SEPARATOR.'validation.php', static::getLang());

        //生成命名空间结构并追加
        $composerJson=file_get_contents(fileSystem::$bathDirPath.'ext'.DIRECTORY_SEPARATOR.'composer.json');
        $data=json_decode($composerJson,true);



        //增加命名空间


        $data['autoload']['psr-4'] = array_merge_recursive($data['autoload']['psr-4'],
            ['LumenV\\' => $newPath.'/'.'provide'],
        [constant::$namespacePrefix.'\\Illuminate\\Support\\'=>'src/provide/support']
        );




        $data=json_encode($data,JSON_UNESCAPED_UNICODE+JSON_UNESCAPED_SLASHES+JSON_PRETTY_PRINT );
        file_put_contents(fileSystem::$bathDirPath.'ext'.DIRECTORY_SEPARATOR.'composer.json', $data);

    }

    private static function baseContent()
    {
        $content = <<<'EOT'
<?php
namespace LumenV;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Translation\FileLoader;
use Illuminate\Translation\Translator;
use Illuminate\Validation\Factory;
use Illuminate\Support\ExtendLoad;

class Validation
{
    private static function getInstance()
    {
        static $factory = NULL;

        if ($factory === NULL) {
            $testTranslationPath = __DIR__.'/lang';

            $testTranslationLocale = 'zn';

            $translationFileLoader = new FileLoader(new Filesystem, $testTranslationPath);

            $translator = new Translator($translationFileLoader, $testTranslationLocale);

            $factory = new Factory($translator);
            
            ExtendLoad::addExtend($factory);

        }

        return $factory;

    }
    
    /**
     * @param          $data
     * @param          $rules
     * @param   array  $messages
     * @param   array  $attributes
     *
     *   返回验证器类  让使用者自定义处理 错误
     */
    public static function cValidate($data, $rules, $messages = [], $attributes = [])
    {
        return static::getInstance()->make($data, $rules, $messages, $attributes);
    }

    public static function validate($data, $rules, $messages = [], $attributes = [])
    {
        $validator = static::getInstance()->make($data, $rules, $messages, $attributes);
        if ($validator->fails()) {
            $errorMessageArray = $validator->errors()->getMessages();
            throw new \Exception(json_encode($errorMessageArray,JSON_UNESCAPED_UNICODE +JSON_UNESCAPED_SLASHES ));
        }

        return $validator->getData();
    }
}
EOT;
        return $content;
    }

    private static function getLang()
    {
        $lang= <<<'EOT'
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the default error messages used by
    | the validator class. Some of these rules have multiple versions such
    | as the size rules. Feel free to tweak each of these messages here.
    |
    */

    'accepted'        => '您必须接受 :attribute。',
    'active_url'      => ':attribute 不是一个有效的网址。',
    'after'           => ':attribute 必须要晚于 :date。',
    'after_or_equal'  => ':attribute 必须要等于 :date 或更晚。',
    'alpha'           => ':attribute 只能由字母组成。',
    'alpha_dash'      => ':attribute 只能由字母、数字、短划线(-)和下划线(_)组成。',
    'alpha_num'       => ':attribute 只能由字母和数字组成。',
    'array'           => ':attribute 必须是一个数组。',
    'before'          => ':attribute 必须要早于 :date。',
    'before_or_equal' => ':attribute 必须要等于 :date 或更早。',
    'between'         => [
        'numeric' => ':attribute 必须介于 :min - :max 之间。',
        'file'    => ':attribute 必须介于 :min - :max KB 之间。',
        'string'  => ':attribute 必须介于 :min - :max 个字符之间。',
        'array'   => ':attribute 必须只有 :min - :max 个单元。',
    ],
    'boolean'        => ':attribute 必须为布尔值。',
    'confirmed'      => ':attribute 两次输入不一致。',
    'date'           => ':attribute 不是一个有效的日期。',
    'date_equals'    => ':attribute 必须要等于 :date。',
    'date_format'    => ':attribute 的格式必须为 :format。',
    'different'      => ':attribute 和 :other 必须不同。',
    'digits'         => ':attribute 必须是 :digits 位数字。',
    'digits_between' => ':attribute 必须是介于 :min 和 :max 位的数字。',
    'dimensions'     => ':attribute 图片尺寸不正确。',
    'distinct'       => ':attribute 已经存在。',
    'email'          => ':attribute 不是一个合法的邮箱。',
    'ends_with'      => ':attribute 必须以 :values 为结尾。',
    'exists'         => ':attribute 不存在。',
    'file'           => ':attribute 必须是文件。',
    'filled'         => ':attribute 不能为空。',
    'gt'             => [
        'numeric' => ':attribute 必须大于 :value。',
        'file'    => ':attribute 必须大于 :value KB。',
        'string'  => ':attribute 必须多于 :value 个字符。',
        'array'   => ':attribute 必须多于 :value 个元素。',
    ],
    'gte' => [
        'numeric' => ':attribute 必须大于或等于 :value。',
        'file'    => ':attribute 必须大于或等于 :value KB。',
        'string'  => ':attribute 必须多于或等于 :value 个字符。',
        'array'   => ':attribute 必须多于或等于 :value 个元素。',
    ],
    'image'    => ':attribute 必须是图片。',
    'in'       => '已选的属性 :attribute 无效。',
    'in_array' => ':attribute 必须在 :other 中。',
    'integer'  => ':attribute 必须是整数。',
    'ip'       => ':attribute 必须是有效的 IP 地址。',
    'ipv4'     => ':attribute 必须是有效的 IPv4 地址。',
    'ipv6'     => ':attribute 必须是有效的 IPv6 地址。',
    'json'     => ':attribute 必须是正确的 JSON 格式。',
    'lt'       => [
        'numeric' => ':attribute 必须小于 :value。',
        'file'    => ':attribute 必须小于 :value KB。',
        'string'  => ':attribute 必须少于 :value 个字符。',
        'array'   => ':attribute 必须少于 :value 个元素。',
    ],
    'lte' => [
        'numeric' => ':attribute 必须小于或等于 :value。',
        'file'    => ':attribute 必须小于或等于 :value KB。',
        'string'  => ':attribute 必须少于或等于 :value 个字符。',
        'array'   => ':attribute 必须少于或等于 :value 个元素。',
    ],
    'max' => [
        'numeric' => ':attribute 不能大于 :max。',
        'file'    => ':attribute 不能大于 :max KB。',
        'string'  => ':attribute 不能大于 :max 个字符。',
        'array'   => ':attribute 最多只有 :max 个单元。',
    ],
    'mimes'     => ':attribute 必须是一个 :values 类型的文件。',
    'mimetypes' => ':attribute 必须是一个 :values 类型的文件。',
    'min'       => [
        'numeric' => ':attribute 必须大于等于 :min。',
        'file'    => ':attribute 大小不能小于 :min KB。',
        'string'  => ':attribute 至少为 :min 个字符。',
        'array'   => ':attribute 至少有 :min 个单元。',
    ],
    'multiple_of'          => 'The :attribute must be a multiple of :value',
    'not_in'               => '已选的属性 :attribute 非法。',
    'not_regex'            => ':attribute 的格式错误。',
    'numeric'              => ':attribute 必须是一个数字。',
    'password'             => '密码错误',
    'present'              => ':attribute 必须存在。',
    'regex'                => ':attribute 格式不正确。',
    'required'             => ':attribute 不能为空。',
    'required_if'          => '当 :other 为 :value 时 :attribute 不能为空。',
    'required_unless'      => '当 :other 不为 :values 时 :attribute 不能为空。',
    'required_with'        => '当 :values 存在时 :attribute 不能为空。',
    'required_with_all'    => '当 :values 存在时 :attribute 不能为空。',
    'required_without'     => '当 :values 不存在时 :attribute 不能为空。',
    'required_without_all' => '当 :values 都不存在时 :attribute 不能为空。',
    'same'                 => ':attribute 和 :other 必须相同。',
    'size'                 => [
        'numeric' => ':attribute 大小必须为 :size。',
        'file'    => ':attribute 大小必须为 :size KB。',
        'string'  => ':attribute 必须是 :size 个字符。',
        'array'   => ':attribute 必须为 :size 个单元。',
    ],
    'starts_with' => ':attribute 必须以 :values 为开头。',
    'string'      => ':attribute 必须是一个字符串。',
    'timezone'    => ':attribute 必须是一个合法的时区值。',
    'unique'      => ':attribute 已经存在。',
    'uploaded'    => ':attribute 上传失败。',
    'url'         => ':attribute 格式不正确。',
    'uuid'        => ':attribute 必须是有效的 UUID。',

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | Here you may specify custom validation messages for attributes using the
    | convention "attribute.rule" to name the lines. This makes it quick to
    | specify a specific custom language line for a given attribute rule.
    |
    */

    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-message',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap our attribute placeholder
    | with something more reader friendly such as "E-Mail Address" instead
    | of "email". This simply helps us make our message more expressive.
    |
    */

    'attributes' => [
        'name'                  => '名称',
        'username'              => '用户名',
        'email'                 => '邮箱',
        'first_name'            => '名',
        'last_name'             => '姓',
        'password'              => '密码',
        'password_confirmation' => '确认密码',
        'city'                  => '城市',
        'country'               => '国家',
        'address'               => '地址',
        'phone'                 => '电话',
        'mobile'                => '手机',
        'age'                   => '年龄',
        'sex'                   => '性别',
        'gender'                => '性别',
        'day'                   => '天',
        'month'                 => '月',
        'year'                  => '年',
        'hour'                  => '时',
        'minute'                => '分',
        'second'                => '秒',
        'title'                 => '标题',
        'content'               => '内容',
        'description'           => '描述',
        'excerpt'               => '摘要',
        'date'                  => '日期',
        'time'                  => '时间',
        'available'             => '可用的',
        'size'                  => '大小',
    ],
];
EOT;
        return $lang;

    }

    private static function extendLoad()
    {
        $extendLoad= <<<'EOT'
<?php
/**
 * Created by PhpStorm.
 * User: 杨帆
 * Date: 2021/2/4
 * Time: 11:03
 */

namespace Fy\Illuminate\Support;

use Fy\Illuminate\Validation\Factory;

class ExtendLoad
{
    public static function addExtend(Factory $factory)
    {
        if (($extendFilesArray = static::dirExistFile(static::getDirExist())) === false) {
            return false;
        }

        $registry = static::getRegistry($extendFilesArray);

        foreach ($registry as $item) {
            $rules = $item['object'];
            $factory->replacer($item['name'], function ($message, $attribute, $rule, $parameters) use ($rules) {
                return $rules->message();
            });

            $factory->extend($item['name'], function ($attribute, $value, $parameters, $validator) use ($rules) {
                return $rules->passes($attribute, $value);
            });
        }
    }


    private static function dirExistFile($path)
    {
        if (!is_dir($path)) {
            return false;
        }

        $files = scandir($path);

        // 删除  "." 和 ".."
        unset($files[0]);
        unset($files[1]);

        // 判断是否为空
        if (!empty($files[2])) {
            return array_values($files);
        }

        return false;
    }

    private static function getDirExist()
    {
        return dirname(dirname(dirname(dirname(__DIR__)))).DIRECTORY_SEPARATOR.'lumen_validation_extend'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Rules';
    }

    /**
     * 转换字符串的格式到下划线的形式
     *
     * CodeType  ->   code_type
     */
    private static function transferClassNameToUnderlineType($string)
    {
        $lowerString      = strtolower($string);
        $lowerStringArray = str_split($lowerString);
        $s                = lcfirst($string);
        $lcfirstArray     = str_split($s);
        $finalStr         = '';
        foreach ($lcfirstArray as $k => $v) {
            if ($v === $lowerStringArray[$k]) {
                $finalStr .= $v;
            } else {
                $finalStr .= $lowerStringArray[$k];
            }
        }

        return $finalStr;
    }

    private static function getRegistry($extendFilesArray)
    {
        $registry = [];
        foreach ($extendFilesArray as $k => $fileNameAll) {
            if (empty($fileName = pathinfo($fileNameAll, PATHINFO_FILENAME))) {
                throw new \Exception('解析文件名称出错:'.$fileNameAll);
            }

            require_once static::getDirExist().DIRECTORY_SEPARATOR.$fileNameAll;

            $registry[] = [
                'name'   => static::transferClassNameToUnderlineType($fileName),
                'object' => new $fileName,
            ];

        }

        return $registry;
    }
}

EOT;
        return $extendLoad;

    }
}

validation::run();
